baseURL: "https://www.agrisoil.us"
languageCode: en-us
title: AgriSoil
paginate: 5
theme: PaperMod
googleAnalytics: G-2P8NXJCLJ8

params:
  showToc: true
  TocOpen: false
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  homeInfoParams:
    Title: "Hello There,"
    Content: "Welcome to AgriSoil! Here you'll find a lot of cool information about a Agriculture Soil. We provides information and resources related to the soil used in agriculture. It covers topics such as soil types, soil health, soil management, and soil conservation. AgriSoil is a valuable resource for farmers, agricultural professionals, and anyone interested in learning more about the role of soil in growing crops and raising livestock. " 
  # socialIcons:
  #   - name: facebook
  #     url: "https://facebook.com/"
  #   - name: twitter
  #     url: "https://twitter.com/"
  #   - name: github
  #     url: "https://github.com/"
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    # - identifier: home
    #   name: Home
    #   url: /
      # weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: home
      name: Home
      url: /
      weight: 60

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary